-- The Ticket-er Telegram Bot Source Code
-- Copyright (C) 2026 Lev (Leo) Kondukov (aka DiceBarrel, Barrel, Vandi)
-- 
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License.
-- 
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.

-- +goose up
-- +goose StatementBegin

create type user_role as enum(
    'pool',
    'blocked',
    'user',
    'admin'
);

create table users (
    id bigint generated by default as identity primary key,
    telegram_id bigint unique,
    balance bigint not null default 0,
    role user_role default 'user' not null,
    updated_at timestamptz not null default current_timestamp,
    created_at timestamptz not null default current_timestamp,
    check (
        balance >= 0
        or role = 'pool'
    )
);

create trigger set_update_users before
update
    on users for each row execute function update_modified_column();

insert into
    users (id, role)
values
    (0, 'pool');

create index idx_user_leaderboard on users (balance desc);
-- +goose StatementEnd